eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: AKASH-LAPTOP
    registerWithEureka: true
    fetchRegistry: true
    preferIpAddress: false
